/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Sat Jun 01 12:34:00 2019. */

#ifndef PB_BLUETOOTH_BLUETOOTH_PB_H_INCLUDED
#define PB_BLUETOOTH_BLUETOOTH_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _bluetooth_BluetoothMessage_MessageType {
    bluetooth_BluetoothMessage_MessageType_BIKE_WHEEL_ANIM = 0,
    bluetooth_BluetoothMessage_MessageType_KALMAN = 1,
    bluetooth_BluetoothMessage_MessageType_BRIGHTNESS = 2,
    bluetooth_BluetoothMessage_MessageType_STORAGE = 3,
    bluetooth_BluetoothMessage_MessageType_BATTERY = 4
} bluetooth_BluetoothMessage_MessageType;
#define _bluetooth_BluetoothMessage_MessageType_MIN bluetooth_BluetoothMessage_MessageType_BIKE_WHEEL_ANIM
#define _bluetooth_BluetoothMessage_MessageType_MAX bluetooth_BluetoothMessage_MessageType_BATTERY
#define _bluetooth_BluetoothMessage_MessageType_ARRAYSIZE ((bluetooth_BluetoothMessage_MessageType)(bluetooth_BluetoothMessage_MessageType_BATTERY+1))

typedef enum _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType {
    bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType_STATIC = 0,
    bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType_D_TIME = 1,
    bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType_D_VEL = 2
} bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType;
#define _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType_MIN bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType_STATIC
#define _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType_MAX bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType_D_VEL
#define _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType_ARRAYSIZE ((bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType)(bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType_D_VEL+1))

typedef enum _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType {
    bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType_CONSTANT = 0,
    bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType_LINEAR = 1
} bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType;
#define _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType_MIN bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType_CONSTANT
#define _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType_MAX bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType_LINEAR
#define _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType_ARRAYSIZE ((bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType)(bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType_LINEAR+1))

typedef enum _bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType {
    bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType_CONST_ROT = 0,
    bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType_SPINNER = 1
} bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType;
#define _bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType_MIN bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType_CONST_ROT
#define _bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType_MAX bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType_SPINNER
#define _bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType_ARRAYSIZE ((bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType)(bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType_SPINNER+1))

/* Struct definitions */
typedef struct _bluetooth_BluetoothLength {
    uint32_t message_length;
/* @@protoc_insertion_point(struct:bluetooth_BluetoothLength) */
} bluetooth_BluetoothLength;

typedef struct _bluetooth_BluetoothMessage_BikeWheelAnim_Color_ {
    pb_callback_t color_objs;
    bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType type;
/* @@protoc_insertion_point(struct:bluetooth_BluetoothMessage_BikeWheelAnim_Color_) */
} bluetooth_BluetoothMessage_BikeWheelAnim_Color_;

typedef struct _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj {
    uint32_t r;
    uint32_t g;
    uint32_t b;
    uint32_t w;
    uint32_t t;
    bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType bt;
/* @@protoc_insertion_point(struct:bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj) */
} bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj;

typedef struct _bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageMetaParameter {
    uint32_t p1;
/* @@protoc_insertion_point(struct:bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageMetaParameter) */
} bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageMetaParameter;

typedef struct _bluetooth_BluetoothMessage_Kalman {
    uint32_t n_obs;
    uint32_t n_sta;
    float q;
    pb_callback_t r;
    pb_callback_t p0;
/* @@protoc_insertion_point(struct:bluetooth_BluetoothMessage_Kalman) */
} bluetooth_BluetoothMessage_Kalman;

typedef struct _bluetooth_BluetoothMessage_Storage {
    uint32_t remaining;
    uint32_t total;
/* @@protoc_insertion_point(struct:bluetooth_BluetoothMessage_Storage) */
} bluetooth_BluetoothMessage_Storage;

typedef struct _bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta {
    bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType type;
    bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageMetaParameter parameter_set;
/* @@protoc_insertion_point(struct:bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta) */
} bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta;

typedef struct _bluetooth_BluetoothMessage_BikeWheelAnim {
    uint32_t num_leds;
    pb_callback_t palette;
    pb_callback_t image_main;
    pb_callback_t image_idle;
    bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta image_meta;
/* @@protoc_insertion_point(struct:bluetooth_BluetoothMessage_BikeWheelAnim) */
} bluetooth_BluetoothMessage_BikeWheelAnim;

typedef struct _bluetooth_BluetoothMessage {
    bluetooth_BluetoothMessage_MessageType type;
    bool request;
    pb_size_t which_contents;
    union {
        bluetooth_BluetoothMessage_BikeWheelAnim bike_wheel_anim;
        bluetooth_BluetoothMessage_Kalman kalman;
        float brightness_scale;
        bluetooth_BluetoothMessage_Storage storage;
        uint32_t battery;
    } contents;
/* @@protoc_insertion_point(struct:bluetooth_BluetoothMessage) */
} bluetooth_BluetoothMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define bluetooth_BluetoothMessage_init_default  {_bluetooth_BluetoothMessage_MessageType_MIN, 0, 0, {bluetooth_BluetoothMessage_BikeWheelAnim_init_default}}
#define bluetooth_BluetoothMessage_BikeWheelAnim_init_default {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_init_default}
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__init_default {{{NULL}, NULL}, _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType_MIN}
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_init_default {0, 0, 0, 0, 0, _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType_MIN}
#define bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_init_default {_bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType_MIN, bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageMetaParameter_init_default}
#define bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageMetaParameter_init_default {0}
#define bluetooth_BluetoothMessage_Kalman_init_default {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define bluetooth_BluetoothMessage_Storage_init_default {0, 0}
#define bluetooth_BluetoothLength_init_default   {0}
#define bluetooth_BluetoothMessage_init_zero     {_bluetooth_BluetoothMessage_MessageType_MIN, 0, 0, {bluetooth_BluetoothMessage_BikeWheelAnim_init_zero}}
#define bluetooth_BluetoothMessage_BikeWheelAnim_init_zero {0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_init_zero}
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__init_zero {{{NULL}, NULL}, _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorType_MIN}
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_init_zero {0, 0, 0, 0, 0, _bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_BlendType_MIN}
#define bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_init_zero {_bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageType_MIN, bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageMetaParameter_init_zero}
#define bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageMetaParameter_init_zero {0}
#define bluetooth_BluetoothMessage_Kalman_init_zero {0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define bluetooth_BluetoothMessage_Storage_init_zero {0, 0}
#define bluetooth_BluetoothLength_init_zero      {0}

/* Field tags (for use in manual encoding/decoding) */
#define bluetooth_BluetoothLength_message_length_tag 1
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__color_objs_tag 1
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__type_tag 2
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_r_tag 1
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_g_tag 2
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_b_tag 3
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_w_tag 4
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_t_tag 5
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_bt_tag 6
#define bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageMetaParameter_p1_tag 1
#define bluetooth_BluetoothMessage_Kalman_n_obs_tag 1
#define bluetooth_BluetoothMessage_Kalman_n_sta_tag 2
#define bluetooth_BluetoothMessage_Kalman_q_tag  3
#define bluetooth_BluetoothMessage_Kalman_r_tag  4
#define bluetooth_BluetoothMessage_Kalman_p0_tag 5
#define bluetooth_BluetoothMessage_Storage_remaining_tag 1
#define bluetooth_BluetoothMessage_Storage_total_tag 2
#define bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_type_tag 1
#define bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_parameter_set_tag 2
#define bluetooth_BluetoothMessage_BikeWheelAnim_num_leds_tag 1
#define bluetooth_BluetoothMessage_BikeWheelAnim_palette_tag 2
#define bluetooth_BluetoothMessage_BikeWheelAnim_image_main_tag 3
#define bluetooth_BluetoothMessage_BikeWheelAnim_image_idle_tag 4
#define bluetooth_BluetoothMessage_BikeWheelAnim_image_meta_tag 5
#define bluetooth_BluetoothMessage_bike_wheel_anim_tag 3
#define bluetooth_BluetoothMessage_kalman_tag    4
#define bluetooth_BluetoothMessage_brightness_scale_tag 5
#define bluetooth_BluetoothMessage_storage_tag   6
#define bluetooth_BluetoothMessage_battery_tag   7
#define bluetooth_BluetoothMessage_type_tag      1
#define bluetooth_BluetoothMessage_request_tag   2

/* Struct field encoding specification for nanopb */
extern const pb_field_t bluetooth_BluetoothMessage_fields[8];
extern const pb_field_t bluetooth_BluetoothMessage_BikeWheelAnim_fields[6];
extern const pb_field_t bluetooth_BluetoothMessage_BikeWheelAnim_Color__fields[3];
extern const pb_field_t bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_fields[7];
extern const pb_field_t bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_fields[3];
extern const pb_field_t bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageMetaParameter_fields[2];
extern const pb_field_t bluetooth_BluetoothMessage_Kalman_fields[6];
extern const pb_field_t bluetooth_BluetoothMessage_Storage_fields[3];
extern const pb_field_t bluetooth_BluetoothLength_fields[2];

/* Maximum encoded size of messages (where known) */
/* bluetooth_BluetoothMessage_size depends on runtime parameters */
/* bluetooth_BluetoothMessage_BikeWheelAnim_size depends on runtime parameters */
/* bluetooth_BluetoothMessage_BikeWheelAnim_Color__size depends on runtime parameters */
#define bluetooth_BluetoothMessage_BikeWheelAnim_Color__ColorObj_size 32
#define bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_size 10
#define bluetooth_BluetoothMessage_BikeWheelAnim_ImageMeta_ImageMetaParameter_size 6
/* bluetooth_BluetoothMessage_Kalman_size depends on runtime parameters */
#define bluetooth_BluetoothMessage_Storage_size  12
#define bluetooth_BluetoothLength_size           5

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BLUETOOTH_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
